### ISSUE TITLE
PNG support

### ISSUE THREAD

**Issue by rebecca-fundy** [Duder-onomy/ember-exif-reader-shim#76]
Does this shim load the latest version of ExifReader?  I am getting an "Invalid image format" error when I upload a PNG, though the ExifReader demo does just fine with them.

Thank you!

**Comment by Duder-onomy** [comment]
Hi, 
It looks like this lib is on `2.3.0` of `exifreader`
I would be happy to update it for you. However, I think the 'favorite' way of importing modules is with [ember-auto-import](https://github.com/ef4/ember-auto-import).

Could you try removing this `ember-exif-reader-shim` from your ember app, then install `ember-auto-import` and `exifreader` and then try importing it directly?

I will update the lib this afternoon and then archive this repo.

**Comment by rebecca-fundy** [comment]
I will try that.  Thanks for the speedy reply!

**Comment by rebecca-fundy** [comment]
I finally got that working.  Thanks again!
